application: auth0-golang-web-app
version: 1
runtime: go
api_version: go1

handlers:
- url: /public
  static_dir: public

- url: /.*
  script: _go_app

env_variables:
  AUTH0_CLIENT_ID: "{CLIENT_ID}"
  AUTH0_DOMAIN: "{DOMAIN}"
  AUTH0_CLIENT_SECRET: "{CLIENT_SECRET}"
  AUTH0_CALLBACK_URL: "http://localhost:8080/callback"
